#!/usr/bin/python
# -*- coding: utf-8 -*-

import csv
import nltk
import random

#---Funktionen---


def transformedData():
    rawData = csv.reader(open("rawData.csv", "rb"))
    listData = [tuple(line)[len(line)-8:] for line in rawData]
    return listData


def rating_features(tuple):
    features = {}
    for feature in range(0, len(tuple)):
        features[descriptionData[feature+1]] = tuple[feature]
    print features
    return features


def classifyTuple(tuple):
    print classifier.classify(rating_features(tuple))

#---Ausfuehrung---

listData = transformedData()
descriptionData = listData.pop(0)
random.shuffle(listData)

ratings = [(listData[i][1:], listData[i][0]) for i in range(0, len(listData))]

featuresets = [(rating_features(n), rating) for (n, rating) in ratings]
train_set, test_set = featuresets[:len(ratings)/2], featuresets[len(ratings)/2:]

classifier = nltk.NaiveBayesClassifier.train(train_set)
classifier.show_most_informative_features(10)

print "Accuracy: ", nltk.classify.accuracy(classifier, test_set)

classifyTuple(("3", "3", "3", "3", "3", "3", "3"))#Beispiel Test-Tupel
